// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: proto/nexus_objects.v1.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// NexusUserObjectV1 represents a sovereign user identity on the network.
// This object defines the core, on-chain attributes of a user.
type NexusUserObjectV1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// A unique, immutable identifier for the user (e.g., a UUID).
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// The user's public key, used for signing content and verifying identity.
	// This is the cryptographic foundation of their sovereignty.
	PublicKey []byte `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	// The user's chosen handle or username. Must be unique across the network.
	Handle string `protobuf:"bytes,3,opt,name=handle,proto3" json:"handle,omitempty"`
	// The timestamp when the user profile was created on-chain.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// A URI (e.g., Arweave or IPFS) pointing to an off-chain JSON object
	// containing mutable metadata like display name, bio, and avatar.
	MetadataUri string `protobuf:"bytes,5,opt,name=metadata_uri,json=metadataUri,proto3" json:"metadata_uri,omitempty"`
}

func (x *NexusUserObjectV1) Reset() {
	*x = NexusUserObjectV1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_nexus_objects_v1_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NexusUserObjectV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NexusUserObjectV1) ProtoMessage() {}

func (x *NexusUserObjectV1) ProtoReflect() protoreflect.Message {
	mi := &file_proto_nexus_objects_v1_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NexusUserObjectV1.ProtoReflect.Descriptor instead.
func (*NexusUserObjectV1) Descriptor() ([]byte, []int) {
	return file_proto_nexus_objects_v1_proto_rawDescGZIP(), []int{0}
}

func (x *NexusUserObjectV1) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *NexusUserObjectV1) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *NexusUserObjectV1) GetHandle() string {
	if x != nil {
		return x.Handle
	}
	return ""
}

func (x *NexusUserObjectV1) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *NexusUserObjectV1) GetMetadataUri() string {
	if x != nil {
		return x.MetadataUri
	}
	return ""
}

// NexusContentObjectV1 represents a piece of content created by a user.
// This is the immutable, on-chain record of a publication.
type NexusContentObjectV1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// A unique, immutable identifier for the content object.
	ContentId string `protobuf:"bytes,1,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`
	// The user_id of the author. This links the content to its sovereign creator.
	AuthorUserId string `protobuf:"bytes,2,opt,name=author_user_id,json=authorUserId,proto3" json:"author_user_id,omitempty"`
	// The timestamp when the content was published on-chain.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// A URI pointing to the actual content body, which is stored off-chain
	// (e.g., on Arweave or another decentralized storage solution).
	ContentBodyUri string `protobuf:"bytes,4,opt,name=content_body_uri,json=contentBodyUri,proto3" json:"content_body_uri,omitempty"`
	// The MIME type of the off-chain content (e.g., "text/markdown", "image/png").
	// This helps clients render the content correctly.
	MimeType string `protobuf:"bytes,5,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	// Frequencies of Resonance (tags) associated with the content, used for
	// filtering and discovery in the "Resonant Conduit".
	Frequencies []string `protobuf:"bytes,6,rep,name=frequencies,proto3" json:"frequencies,omitempty"`
}

func (x *NexusContentObjectV1) Reset() {
	*x = NexusContentObjectV1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_nexus_objects_v1_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NexusContentObjectV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NexusContentObjectV1) ProtoMessage() {}

func (x *NexusContentObjectV1) ProtoReflect() protoreflect.Message {
	mi := &file_proto_nexus_objects_v1_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NexusContentObjectV1.ProtoReflect.Descriptor instead.
func (*NexusContentObjectV1) Descriptor() ([]byte, []int) {
	return file_proto_nexus_objects_v1_proto_rawDescGZIP(), []int{1}
}

func (x *NexusContentObjectV1) GetContentId() string {
	if x != nil {
		return x.ContentId
	}
	return ""
}

func (x *NexusContentObjectV1) GetAuthorUserId() string {
	if x != nil {
		return x.AuthorUserId
	}
	return ""
}

func (x *NexusContentObjectV1) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *NexusContentObjectV1) GetContentBodyUri() string {
	if x != nil {
		return x.ContentBodyUri
	}
	return ""
}

func (x *NexusContentObjectV1) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *NexusContentObjectV1) GetFrequencies() []string {
	if x != nil {
		return x.Frequencies
	}
	return nil
}

var File_proto_nexus_objects_v1_proto protoreflect.FileDescriptor

var file_proto_nexus_objects_v1_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6e, 0x65, 0x78, 0x75, 0x73, 0x5f, 0x6f, 0x62,
	0x6a, 0x65, 0x63, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08,
	0x6e, 0x65, 0x78, 0x75, 0x73, 0x2e, 0x76, 0x31, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xc1, 0x01, 0x0a, 0x11, 0x4e, 0x65,
	0x78, 0x75, 0x73, 0x55, 0x73, 0x65, 0x72, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x56, 0x31, 0x12,
	0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x75, 0x62, 0x6c,
	0x69, 0x63, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x70, 0x75,
	0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x61, 0x6e, 0x64, 0x6c,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x12,
	0x39, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52,
	0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x6d, 0x65,
	0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x75, 0x72, 0x69, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x55, 0x72, 0x69, 0x22, 0xff, 0x01,
	0x0a, 0x14, 0x4e, 0x65, 0x78, 0x75, 0x73, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x4f, 0x62,
	0x6a, 0x65, 0x63, 0x74, 0x56, 0x31, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x24, 0x0a, 0x0e, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x5f,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x61,
	0x75, 0x74, 0x68, 0x6f, 0x72, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x39, 0x0a, 0x0a, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x28, 0x0a, 0x10, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x5f, 0x62, 0x6f, 0x64, 0x79, 0x5f, 0x75, 0x72, 0x69, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0e, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x42, 0x6f, 0x64, 0x79, 0x55, 0x72, 0x69,
	0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x69, 0x6d, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x6d, 0x69, 0x6d, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x20, 0x0a,
	0x0b, 0x66, 0x72, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x69, 0x65, 0x73, 0x18, 0x06, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x0b, 0x66, 0x72, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x69, 0x65, 0x73, 0x42,
	0x44, 0x5a, 0x42, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x42, 0x69,
	0x67, 0x42, 0x6f, 0x73, 0x73, 0x42, 0x6f, 0x6f, 0x6c, 0x69, 0x6e, 0x67, 0x42, 0x2f, 0x44, 0x69,
	0x67, 0x69, 0x74, 0x61, 0x6c, 0x2d, 0x47, 0x6f, 0x6c, 0x65, 0x6d, 0x2d, 0x45, 0x6e, 0x67, 0x69,
	0x6e, 0x65, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6e, 0x65, 0x78,
	0x75, 0x73, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_nexus_objects_v1_proto_rawDescOnce sync.Once
	file_proto_nexus_objects_v1_proto_rawDescData = file_proto_nexus_objects_v1_proto_rawDesc
)

func file_proto_nexus_objects_v1_proto_rawDescGZIP() []byte {
	file_proto_nexus_objects_v1_proto_rawDescOnce.Do(func() {
		file_proto_nexus_objects_v1_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_nexus_objects_v1_proto_rawDescData)
	})
	return file_proto_nexus_objects_v1_proto_rawDescData
}

var file_proto_nexus_objects_v1_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_nexus_objects_v1_proto_goTypes = []interface{}{
	(*NexusUserObjectV1)(nil),     // 0: nexus.v1.NexusUserObjectV1
	(*NexusContentObjectV1)(nil),  // 1: nexus.v1.NexusContentObjectV1
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_proto_nexus_objects_v1_proto_depIdxs = []int32{
	2, // 0: nexus.v1.NexusUserObjectV1.created_at:type_name -> google.protobuf.Timestamp
	2, // 1: nexus.v1.NexusContentObjectV1.created_at:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_nexus_objects_v1_proto_init() }
func file_proto_nexus_objects_v1_proto_init() {
	if File_proto_nexus_objects_v1_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_nexus_objects_v1_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NexusUserObjectV1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_nexus_objects_v1_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NexusContentObjectV1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_nexus_objects_v1_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_nexus_objects_v1_proto_goTypes,
		DependencyIndexes: file_proto_nexus_objects_v1_proto_depIdxs,
		MessageInfos:      file_proto_nexus_objects_v1_proto_msgTypes,
	}.Build()
	File_proto_nexus_objects_v1_proto = out.File
	file_proto_nexus_objects_v1_proto_rawDesc = nil
	file_proto_nexus_objects_v1_proto_goTypes = nil
	file_proto_nexus_objects_v1_proto_depIdxs = nil
}
